version: "3"
services:
  pgvector:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: midsearch
      POSTGRES_USER: midsearch
      POSTGRES_PASSWORD: midsearch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  midsearch:
    build: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: postgresql://midsearch:midsearch_password@pgvector:5432/midsearch
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}

  # Uncomment to enable telegram bot
  # telegram-bot:
  #   build: .
  #   environment:
  #     MIDSEARCH_ENDPOINT: http://midsearch:8080/api/
  #     MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}
  #     TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
  #   command: python3 midsearch/client telegram

  # Uncomment to enable discord bot
  # discord-bot:
  #   build: .
  #   environment:
  #     MIDSEARCH_ENDPOINT: http://midsearch:8080/api/
  #     MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}
  #     DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
  #   command: python3 midsearch/client discord

  # Uncomment to enable mirai bot
  # mirai-bot:
  #   build: .
  #   environment:
  #     MIDSEARCH_ENDPOINT: http://midsearch:8080/api/
  #     MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}
  #     MIRAI_BOT_QQ: ${MIRAI_BOT_QQ}
  #     MIRAI_VERIFY_KEY: ${MIRAI_VERIFY_KEY}
  #     MIRAI_HTTP_URL: ${MIRAI_HTTP_URL}
  #     MIRAI_WS_URL: ${MIRAI_WS_URL}
  #   command: python3 midsearch/client mirai

  # mirai:
  #   image: lss233/mirai-http:latest
  #   restart: always
  #   environment:
  #     LANG: 'C.UTF-8'
  #   ports:
  #     - 5700:5700
  #     - 5701:5701
  #   volumes:
  #     - mirai_data:/app/data
  #     - mirai_bots:/app/bots
  #     - ./etc/mirai-api-http/setting.yml:/app/config/net.mamoe.mirai-api-http/setting.yml

volumes:
  postgres_data:
  mirai_data:
  mirai_bots:
