version: "3"
services:
   pgvector:
     image: ankane/pgvector
     ports:
       - 5432:5432
     environment:
       POSTGRES_DB: midsearch
       POSTGRES_USER: midsearch
       POSTGRES_PASSWORD: midsearch_password
     volumes:
       - postgres_data:/var/lib/postgresql/data

volumes:
   postgres_data:
