version: "3"
services:
  pgvector:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: midsearch
      POSTGRES_USER: midsearch
      POSTGRES_PASSWORD: midsearch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  midsearch:
    build: .
    ports:
      - 5000:5000
    environment:
      POSTGRES_URL: postgresql://midsearch:midsearch_password@pgvector:5432/midsearch
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  telegram-bot:
    build: .
    environment:
      MIDSEARCH_ENDPOINT: http://midsearch:5000/api/
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    command: python3 midsearch telegram

  wechaty:
    image: wechaty/wechaty:0.65
    environment:
      WECHATY_LOG: verbose
      WECHATY_PUPPET: wechaty-puppet-padlocal
      WECHATY_PUPPET_PADLOCAL_TOKEN: ${WECHATY_PUPPET_PADLOCAL_TOKEN}
      WECHATY_PUPPET_SERVER_PORT: 8080
      WECHATY_TOKEN: ${WECHATY_TOKEN}
    ports:
      - 8080:8080

volumes:
  postgres_data:
