version: "3"
services:
  pgvector:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: midsearch
      POSTGRES_USER: midsearch
      POSTGRES_PASSWORD: midsearch_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  midsearch:
    build: .
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: postgresql://midsearch:midsearch_password@pgvector:5432/midsearch
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}

  telegram-bot:
    build: .
    environment:
      MIDSEARCH_ENDPOINT: http://midsearch:8080/api/
      MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    command: python3 midsearch/client telegram

  discord-bot:
    build: .
    environment:
      MIDSEARCH_ENDPOINT: http://midsearch:8080/api/
      MIDSEARCH_API_KEY: ${MIDSEARCH_API_KEY}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    command: python3 midsearch/client discord

volumes:
  postgres_data:
