name: build

on:
  push:
    branches:    
      - main

jobs:
  docker_images:
    name: docker images
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        uses: docker/build-push-action@v2.6.1
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: zhenghaoz/midsearch:nightly
          
      - name: Resolve Images on Description
        run: |
          sed -i -E "s/src=\"assets\//src=\"https:\/\/github.com\/gorse-io\/midsearch\/raw\/main\/assets\//" README.md
          
      - name: Update DockerHub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: zhenghaoz/midsearch
