name: test

on:
  push:
    branches:
      - main
      - 'release-**'
  pull_request:
    branches:
      - main
      - 'release-**'

jobs:
  unit_test:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    services:
      pgvector:
        image: ankane/pgvector
        env:
          POSTGRES_DB: midsearch
          POSTGRES_USER: midsearch
          POSTGRES_PASSWORD: midsearch_password
        ports:
          - 5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
        env:
          PYTHONPATH: ${{ github.workspace }}
          POSTGRES_URL: postgresql://midsearch:midsearch_password@localhost:${{ job.services.pgvector.ports[5432] }}/midsearch
